language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
env:
    - REACTOR=select
    - REACTOR=epoll
addons:
    apt:
        packages:
            - libzmq3-dev
install:
    - pip install -r requirements.txt
script:
    - >-
        [ ! -f $VIRTUAL_ENV/bin/trial ] || PYTHONPATH=. coverage run $VIRTUAL_ENV/bin/trial --reactor=$REACTOR txzmq
    - >-
        [ -f $VIRTUAL_ENV/bin/trial ] || PYTHONPATH=. nosetests
    - pep8 --repeat txzmq
    - pyflakes txzmq
    - python examples/integration_test.py
after_success:
    - coveralls
notifications:
    email:
        - me@smira.ru
matrix:
    allow_failures:
        - python: pypy
        - python: pypy3
